# Generated by Django 4.0.4 on 2022-05-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_body1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body1',
        ),
    ]
